vc_metro = {
    'Gajjumata': set(['Kahna']),
    'Kahna': set(['Gajjumata', 'Yuhanabad']),
    'Yuhanabad': set(['Kahna', 'Nishtar Colony']),
    'Nishtar Colony': set(['Yuhanabad', 'Dulu Khurd']),
    'Dulu Khurd': set(['Nishtar Colony', 'Youhanabad Chowk']),
    'Youhanabad Chowk': set(['Dulu Khurd', 'Attari Saroba']),
    'Attari Saroba': set(['Youhanabad Chowk', 'Chungi Amar Sidhu']),
    'Chungi Amar Sidhu': set(['Attari Saroba', 'Qainchi']),
    'Qainchi': set(['Chungi Amar Sidhu', 'Ghazi Road']),
    'Ghazi Road': set(['Qainchi', 'Kalma Chowk']),
    'Kalma Chowk': set(['Ghazi Road', 'Model Town']),
    'Model Town': set(['Kalma Chowk', 'Ichra']),
    'Ichra': set(['Model Town', 'Shama']),
    'Shama': set(['Ichra', 'Qurtaba Chowk']),
    'Qurtaba Chowk': set(['Shama', 'M.A.O College']),
    'M.A.O College': set(['Qurtaba Chowk', 'Janazgah']),
    'Janazgah': set(['M.A.O College', 'Civil Secretariat']),
    'Civil Secretariat': set(['Janazgah', 'Azadi Chowk']),
    'Azadi Chowk': set(['Civil Secretariat', 'Timber Market']),
    'Timber Market': set(['Azadi Chowk', 'Bhatti Chowk']),
    'Bhatti Chowk': set(['Timber Market', 'Mochi Gate']),
    'Mochi Gate': set(['Bhatti Chowk', 'Janazgah']),
}
